import test from 'node:test';
import assert from 'node:assert/strict';
import {Candidate,Evidence,Source,assess,selectPilot} from './engine';
import {signToken,verifyToken,contactHash} from './security';
import {sequence} from './emails';
const now='2026-09-07T12:00:00Z';
const sources:Source[]=[{id:'owned',domain:'example.com',terms_url:'https://example.com/terms',reviewed_at:now,research:'allowed',outreach:'allowed',automated_fetch:false,basis:'Synthetic fixture permission, not a real source authorization'}];
function ev(id:string,kind:Evidence['kind'],value:Evidence['value'],at=now):Evidence{return {id,kind,value,source_id:'owned',url:'https://example.com/sale',observed_at:at,excerpt:'Synthetic fixture',verified:true};}
function candidate():Candidate{return {id:'signal_001',entity_key:'business_001',listing_url:'https://example.com/sale',source_id:'owned',business_name:'Fictional Shop',public_listing_label:'Fictional Shop',country:'US',state:'CA',sector:'Services',asking_price:500000,currency:'USD',revenue:750000,cash_flow:150000,operating_company:true,owner_operated:true,representation:'owner_direct',status:'active',original_published_at:'2024-09-01T12:00:00Z',first_seen_at:now,last_updated_at:now,active_verified_at:now,evidence:[ev('original','original_published_at','2024-09-01T12:00:00Z'),ev('active','active',true)],resolution:{confidence:'high',evidence_urls:['https://example.com/sale','https://example.com/about'],notes:'Synthetic test',confidential:false},contact:{id:'contact_001',email:'owner@example.com',audience:'seller',entity_key:'person_001',source_id:'owned',source_url:'https://example.com/about',verified_at:now,role_verified:true,us_verified:true,business_email:true,provider_verified:true}};}
test('a refreshed two-year-old listing is not new',()=>{const r=assess(candidate(),sources,now);assert.equal(r.components.duration,35);assert.equal(r.first_seen_age_days,0);assert.equal(r.age_basis,'verified_original');assert.equal(r.outreach_ready,true);});
test('first seen never fabricates original publication',()=>{const c=candidate();c.original_published_at=null;c.first_seen_at='2020-01-01';c.evidence=c.evidence.filter(e=>e.kind!=='original_published_at');const r=assess(c,sources,now);assert.equal(r.original_listing_age_days,null);assert.equal(r.components.duration,0);});
test('observed duration is explicitly a lower bound',()=>{const c=candidate();c.original_published_at=null;c.evidence=[ev('old','active',true,'2025-01-01'),ev('new','active',true)];const r=assess(c,sources,now);assert.equal(r.components.duration,35);assert.equal(r.age_basis,'observed_lower_bound');});
test('unverified, future, and blocked evidence cannot contribute',()=>{const c=candidate();c.evidence=[{...ev('original','original_published_at',c.original_published_at!),verified:false},ev('price','price_reduced',true,'2030-01-01')];assert.equal(assess(c,sources,now).score,0);assert.equal(assess(candidate(),[{...sources[0],research:'blocked'}],now).score,0);});
test('multiple price changes compare the same package and do not double count copy',()=>{const c=candidate();c.evidence.push({...ev('p1','price',600000,'2026-07-01'),comparable_basis:'business_ex_re_usd'},{...ev('p2','price',500000,'2026-08-01'),comparable_basis:'business_ex_re_usd'},{...ev('p3','price',400000),comparable_basis:'business_ex_re_usd'},ev('copy','price_reduced',true));let r=assess(c,sources,now);assert.equal(r.reduction_count,2);assert.equal(r.components.repricing,25);c.evidence.find(e=>e.id==='p2')!.comparable_basis='assets_only';c.evidence.find(e=>e.id==='p3')!.comparable_basis='assets_only_2';r=assess(c,sources,now);assert.equal(r.reduction_count,1);assert.equal(r.reduction_pct,null);});
test('seller financing needs change evidence; urgency phrases are capped',()=>{const c=candidate();c.evidence.push(ev('fin','seller_financing_added',true),ev('u1','urgency','must_sell'),ev('u2','urgency','motivated_seller'));let r=assess(c,sources,now);assert.equal(r.components.terms,0);assert.equal(r.components.urgency,8);c.evidence.find(e=>e.id==='fin')!.explicit_change_statement=true;assert.equal(assess(c,sources,now).components.terms,8);});
test('closed, stale, anonymous, or brokered sellers cannot receive seller outreach',()=>{for(const mutation of [(c:Candidate)=>c.status='sold',(c:Candidate)=>c.active_verified_at='2026-08-01',(c:Candidate)=>c.representation='broker',(c:Candidate)=>c.resolution.confidential=true]){const c=candidate();mutation(c);assert.equal(assess(c,sources,now).outreach_ready,false);}});
test('qualification is separate from contact resolution and source outreach clearance',()=>{const c=candidate();delete c.contact;const r=assess(c,sources,now);assert.equal(r.qualified,true);assert.equal(r.outreach_ready,false);assert.equal(assess(candidate(),[{...sources[0],outreach:'pending'}],now).outreach_ready,false);});
test('cohorts dedupe businesses, contacts, and brokers and cap 25 per route',()=>{const rows:Candidate[]=[];for(let i=0;i<40;i++){const c=candidate();c.id='sig_'+i;c.entity_key='biz_'+i;c.contact!.id='contact_'+i;c.contact!.entity_key='person_'+i;c.contact!.email='owner'+i+'@example.com';rows.push(c);}const p=selectPilot(rows,sources,now);assert.equal(p.counts.seller,25);rows.forEach(c=>{c.representation='broker';c.contact!.audience='broker';c.contact!.email='broker@example.com';});assert.equal(selectPilot(rows,sources,now).counts.broker,1);});
test('campaign tokens reject tampering, expiration, wrong purpose; unsubscribe has no expiry',()=>{const secret='test_'.repeat(10);const token=signToken({v:1,purpose:'campaign',signal:'signal_001',contact:'contact_001',audience:'seller',step:0,exp:1800000000},secret);assert.ok(verifyToken(token,secret,'campaign',1700000000000));assert.equal(verifyToken(token+'x',secret,'campaign',1700000000000),null);assert.equal(verifyToken(token,secret,'unsubscribe'),null);assert.equal(verifyToken(token,secret,'campaign',1900000000000),null);const opt=signToken({v:1,purpose:'unsubscribe',contact:'contact_001'},secret);assert.ok(verifyToken(opt,secret,'unsubscribe',2100000000000));assert.equal(contactHash(' OWNER@EXAMPLE.COM ',secret),contactHash('owner@example.com',secret));});
test('email cannot claim another price cut without reduction evidence',()=>{const c=candidate();const urls={score:'https://example.com/score',partners:'https://example.com/partners',sample:'https://example.com/sample',unsubscribe:'https://example.com/unsubscribe'};let messages=sequence(c,sources,urls,'Approved fixture address',now);assert.equal(messages[0].subject,'A lower asking price may not fix it');assert.match(messages[0].body,/Commercial message/);assert.match(messages[0].body,/Unsubscribe/);c.evidence.push(ev('cut','price_reduced',true));messages=sequence(c,sources,urls,'Approved fixture address',now);assert.equal(messages[0].subject,'Before you cut the price again');assert.deepEqual(messages.map(m=>m.day),[0,4,10]);});
