import { MIKE_ACQUISITION_DOCTRINE, ACQUISITION_DOCTRINE_AUTHORITY_NOTE } from './doctrine';
import { BUYER_INTAKE_FIELDS, type BuyerIntake } from './buyer-intake';
import type { BuyerDiagnosticReport } from './buyer-diagnostic';
import type { ReasonedAssessment } from './reasoning-contract';
const refs = ['buyer-intake'];
const a = (conclusion: string, analysis: string, implications: string): ReasonedAssessment => ({ conclusion, analysis, implications, evidenceIds: refs });
export const BUYER_SAMPLE_INTAKE: BuyerIntake = {
  version: '1.0.0', segment: 'strategic', publicResearch: null,
  answers: { ...Object.fromEntries(BUYER_INTAKE_FIELDS.map(f => [f[0],null])), companyName: 'Harbor Field Services — fictional sample', companyDescription: 'Fictional regional commercial equipment maintenance business with 18 employees. An adjacent operator is evaluating geographic expansion. All facts and competitor names in this example are invented for demonstration.', industry: 'Commercial equipment maintenance', geography: 'Southern California (illustrative)', buyerType: 'Adjacent strategic operator with an existing dispatch and finance team', buyerThesis: 'Expand regional coverage and acquire a trained field team while preserving customer relationships.', revenue: '$4.0M in fictional FY2025', earnings: '$600K seller-adjusted EBITDA, including $120K of adjustments; period FY2025', financialTrajectory: 'Revenue increased 8%; adjusted margin unchanged. No monthly statements provided.', addBacks: '$80K owner salary adjustment and $40K described as one-time software implementation. Replacement management cost not supplied.', askingPrice: '$3.0M enterprise value; cash/debt and working-capital provisions not agreed.', financing: 'Buyer expects to use acquisition debt but has no term sheet or modeled downside.', revenueModel: '65% described as recurring maintenance; only 30% of total revenue is under written annual contracts. Renewals and cancellation provisions unreviewed.', customerConcentration: 'Largest customer 28% of revenue. Owner holds the primary relationship.', ownerDependence: 'Owner leads key accounts, pricing exceptions and complex service escalations. Offers 90-day transition.', management: 'Experienced field supervisor but no identified general manager. Two senior technicians hold specialist knowledge.', financialEvidence: 'Seller summary P&L only; no GL, balance sheet, or cash-flow statement.', competitors: 'Fictional alternatives: Metro Equipment Care, a broad-service regional provider, and Precision Plant Service, a specialist response provider. Their capabilities are buyer assertions, not researched findings.', defensibility: 'Seller claims fast response and a skilled technician base; contract, retention, and service-level evidence not supplied.', sellerMotivation: 'Retirement; seller says the team can run the business without them.', controlAndStructure: 'Founder says they own 70%; minority consent and contract transfer terms not supplied.', questions: 'Is the technician/customer base transferable, and should the buyer spend on diligence?' } as BuyerIntake['answers'],
};
export const BUYER_SAMPLE_REPORT: BuyerDiagnosticReport = {
  version: '1.0.0', reportId: 'illustrative-harbor-001', generatedAt: '2026-09-05T00:00:00.000Z', companyName: 'Harbor Field Services — fictional sample', segment: 'strategic', doctrineIds: MIKE_ACQUISITION_DOCTRINE.map(p => p.id),
  research: { status: 'not_requested', summary: 'Illustrative assessment of a fictional company. No live model or external research call produced this sample.', sources: [], researchedAt: null },
  sourceRegister: [{ id: 'buyer-intake', label: 'Fictional Harbor deal packet', basis: 'Invented facts and competitor names for demonstration; not a real company, transaction, or independently verified diligence.', url: null }], authorityNote: ACQUISITION_DOCTRINE_AUTHORITY_NOTE,
  draft: {
    provisionalPosture: 'investigate',
    investmentCommitteeSnapshot: { headline: 'A regional service capability whose transferability has not yet been established.', transactionFrame: 'Harbor is presented as a $4.0M maintenance business with 18 employees and $600K of seller-adjusted EBITDA (earnings before interest, taxes, depreciation and amortization). The buyer seeks regional coverage and technical staff. The acquisition case depends on retaining customers and specialist technicians after an owner-led transition.', definingOpportunity: 'An existing service footprint and trained field team could accelerate expansion beyond what organic recruiting alone would deliver.', definingUncertainty: 'The owner controls the largest account and operating exceptions, while the seller’s earnings adjustments exclude an unquantified replacement-management cost.', reliancePosture: 'screen_grade' },
    decisionInterpretation: 'Investigate with a narrow evidence gate before commissioning broader diligence. The overlapping customer, owner, and earnings issues make this a transferability question first. They are not three independent discounts that can simply be added together. A loss of the largest account could weaken cash flow precisely as replacement management and debt service increase cash requirements. No value conclusion or LOI approval is supported by the present packet.',
    companyAssessment: a('The buyer is acquiring a service-delivery system, not simply a book of maintenance revenue.', 'Harbor’s dispatch coverage, technical response capability and customer relationships must continue together. Eighteen employees establish scale, but do not demonstrate management independence. The owner still controls pricing exceptions and escalations. A buyer that removes that decision point without replacing it may acquire capacity that cannot operate at the seller’s service standard.', 'Map the functions performed by the owner and the two specialist technicians, then identify who will perform each function after closing.'),
    competitiveLandscape: a('The named alternatives expose a choice between coverage and specialist responsiveness.', 'The fictional buyer packet describes Metro Equipment Care as a broad-service regional provider and Precision Plant Service as a specialist response provider. These are illustrative buyer assertions, not researched competitor facts. If Harbor wins because it responds faster, the diligence question is whether that response comes from repeatable dispatch processes or the owner personally resolving exceptions. If it wins on specialist capability, retention of the two senior technicians matters more than the headcount total.', 'Obtain win/loss examples, customer references and response-time records. Test whether the proposed buyer improves the attribute customers actually value rather than imposing a service model designed for a different competitor.'),
    industryAssessment: a('A recurring service need can support durable demand while leaving the provider replaceable.', 'Maintenance demand and Harbor’s ability to retain that demand are separate questions. The illustrative packet does not establish the installed equipment base, customer capex cycles, regulatory service requirements, or the intensity of regional consolidation. Calling the sector defensive or fragmented would not resolve those gaps. The buyer also needs to understand which equipment categories require scarce certifications and which work can be bid out among interchangeable providers.', 'Research equipment mix and service requirements, then compare local providers and OEM service alternatives. Do not capitalize a generic industry narrative into the purchase price.'),
    thesisAssessment: a('Geographic expansion is plausible; the speed advantage over building remains unmeasured.', 'The acquisition could provide immediate technicians, accounts and route density. But the buyer already has dispatch and finance capabilities. Those existing capabilities create potential value for the buyer; they do not demonstrate that Harbor’s standalone earnings justify the seller’s ask. The alternative is to recruit a team and add coverage progressively, accepting a slower ramp and potentially avoiding inherited concentration.', 'Compare acquisition with recruiting, partnership and waiting. Separate the time-to-market benefit from revenue that could migrate after a poor transition.'),
    buyerFitAssessment: a('The buyer’s shared services address support functions more readily than account ownership.', 'An existing dispatch and finance team may reduce administrative duplication. It does not automatically replace the owner’s customer authority or technical judgment. The experienced field supervisor is a potential transition anchor, but no evidence establishes capacity to manage commercial negotiations, escalation decisions and hiring while retaining current field duties.', 'Name the post-close operating leader and obtain a role-by-role transition plan before crediting integration savings.'),
    economicsInterpretation: a('The asking price cannot be evaluated against a sustainable earnings base yet.', 'The $600K EBITDA figure includes $120K of seller adjustments. The $80K owner salary adjustment is not transferable earnings if the owner’s duties require a paid replacement. The $40K software item may be nonrecurring, partially recurring or associated with an incomplete implementation; invoices and support contracts are missing. No accepted normalization, enterprise-to-equity bridge, working-capital requirement or modeled buyer cash flow has been supplied.', 'Build those calculations from supported inputs using the existing underwriting workflow. Establish the buyer’s private ceiling before negotiating a range. Buyer-specific savings should remain separate from standalone value.'),
    revenueQuality: a('The recurring label is broader than the documented contract base.', 'Harbor describes 65% of revenue as recurring maintenance, but only 30% of total revenue is reported under written annual contracts. Repeat service can be durable without a contract; the problem is treating repeat behavior as enforceable commitment. Neither category establishes renewal probability, cancellation rights or transferability after a change in control.', 'Separate contracted maintenance, repeat noncontracted service and one-time work. Reconcile each category to invoices and test retention across cohorts.'),
    earningsQuality: a('Owner replacement and software treatment could materially change the earnings the buyer receives.', 'The seller has supplied a summary P&L rather than records that permit financial reconstruction. Revenue growth of 8% with a flat adjusted margin is not proof of improving operating leverage. Changes in the adjustment policy, overtime, technician utilization or deferred spending could obscure the underlying trajectory.', 'Reconstruct monthly results from the general ledger and tie material items to invoices, payroll, bank records and tax filings. Accept each add-back only after establishing its treatment after closing.'),
    cashConversion: a('Reported EBITDA does not show when customer revenue becomes usable cash.', 'No receivables aging, billing-cycle information or cash-flow statement is available. A maintenance provider can report stable earnings while financing payroll and parts ahead of collections. That timing gap becomes especially important if the largest account pays slowly or a new owner changes invoice approval routines.', 'Request aging reports and monthly cash collections. Build seasonal cash requirements alongside debt service rather than treating the year-end cash balance as the whole liquidity need.'),
    ownerDependence: a('The proposed 90-day handover is not supported by a transfer plan.', 'The owner holds the largest relationship and resolves operational exceptions, yet says the team can run independently. That contradiction is a diligence lead, not proof of deliberate misrepresentation. A handover date matters less than whether account introductions, escalation authority and technical knowledge have moved to named people.', 'Tie transition milestones to observable transfer of responsibilities. Test the supervisor’s actual decision authority before assuming the owner can leave on schedule.'),
    managementDepth: a('Technical experience and general-management capacity must be evaluated separately.', 'The field supervisor and two specialist technicians may carry much of Harbor’s practical capability. Elevating the supervisor without backfilling field duties could create a new service bottleneck. Retention risk may also rise if employees interpret the acquisition as a signal of immediate consolidation or changed compensation.', 'Develop role, capacity and retention plans before announcing integration targets. Budget replacement and retention costs explicitly.'),
    customerConcentration: a('The 28% customer and owner dependence form a single concentrated transition exposure.', 'The largest customer relationship is not just a revenue concentration statistic: it is mediated by the departing owner. The buyer cannot judge its durability from tenure alone. Service history, contract terms, switching alternatives and the identity of the customer’s decision-maker all affect what can transfer.', 'Review the contract and service record first. With appropriate process authorization, test transition expectations with the customer before treating the account as retained.'),
    workingCapital: a('A working-capital peg has not been established.', 'The seller’s $3.0M enterprise-value ask does not define the operating assets and liabilities delivered at closing. Receivables, parts inventory, deferred revenue and ordinary-course payables can materially alter cash required and the economics of the deal. There is no basis for substituting an assumed zero adjustment.', 'Use monthly balances to establish normal operating working capital and identify aged receivables or obsolete inventory requiring separate treatment.'),
    capitalExpenditure: a('Maintenance investment could be hidden behind the adjusted-earnings narrative.', 'The packet contains no fleet, tools, equipment or software replacement schedule. The software add-back is especially relevant because it may reflect growth investment or a transition still requiring spending. Deferred maintenance should not become accepted recurring earnings merely because the seller postponed a purchase.', 'Inspect asset condition and distinguish maintenance, catch-up and discretionary growth spending. Reflect cash requirements in underwriting rather than inventing an earnings adjustment.'),
    aiExposure: a('Dispatch efficiency could improve without creating a defensible moat.', 'Routing, scheduling and administrative automation may help the buyer serve this footprint more efficiently. Those tools can also be available to competitors. The harder-to-replace capability may be field expertise and response reliability, both of which depend on retaining the people and operating practices that produce them.', 'Assess adoption against measurable service and margin improvements. Do not pay a premium for an AI opportunity that the buyer will have to fund and execute.'),
    financing: a('Bankability remains unknown because sustainable cash flow and the proposed debt terms are missing.', 'The buyer expects debt financing but has no lender terms or modeled downside. The interaction of customer loss, replacement management, working capital and debt service is more important than a headline leverage assumption. Financing availability, even if obtained, would not establish that the price is economically supportable.', 'Model revenue decline and margin compression together, including debt service and required cash. A non-survivable worst case is a stop under Mike’s framework.'),
    integration: a('Protect the customer-facing service operation while testing back-office integration.', 'Moving finance and support processes may be practical earlier than changing account ownership, technician scheduling or escalation paths. Combining everything at closing would obscure whether any service deterioration came from the target or the buyer’s changes. A period of standalone operating visibility may also be useful if contingent consideration is agreed.', 'Assign owners and milestones to integration actions. Preserve customer-facing continuity and a clear operating baseline while validating support-function savings.'),
    sellerMotivation: a('Retirement is consistent with a sale, but not yet with the claimed independence of the business.', 'A 90-day transition and the statement that the team runs independently sit uneasily beside the owner’s control of key accounts and escalation decisions. The founder also reports only 70% ownership. Majority ownership alone does not establish every consent required to deliver the proposed transaction.', 'Request ownership records and identify required approvals. Test the seller’s willingness to support a credible transition and resolve inconsistencies before the buyer commits to exclusivity.'),
    findings: [
      { id: 'transfer', dimension: 'owner_dependence', title: 'Largest-account transfer depends on the owner', rating: 'high', disposition: 'investigate', evidenceIds: refs, implication: 'Customer and management risks could crystallize at the same time.', requiredAction: 'Verify the account’s contract and establish named relationship coverage.' },
      { id: 'earnings', dimension: 'earnings_quality', title: 'Adjusted earnings omit an unknown replacement cost', rating: 'high', disposition: 'price', evidenceIds: refs, implication: 'The seller’s earnings denominator may overstate transferable economics.', requiredAction: 'Normalize owner costs and substantiate the software adjustment before valuation.' },
      { id: 'consent', dimension: 'legal_regulatory', title: 'Transaction authority is not established', rating: 'unknown', disposition: 'investigate', evidenceIds: refs, implication: 'The seller may not yet have a credible path to deliver the proposed transaction.', requiredAction: 'Obtain the cap table and relevant voting and consent provisions.' },
    ],
    diligencePressureMap: [
      { rank: 1, area: 'Customer and owner transferability', whyItMatters: 'A concentrated customer loss could impair the whole transaction case.', evidenceRequired: 'Contract, service history, relationship map and transition responsibilities.', decisionAffected: 'Whether to continue diligence at all.', evidenceIds: refs },
      { rank: 2, area: 'Sustainable earnings and required capital', whyItMatters: 'Unsupported add-backs and replacement spending distort affordability.', evidenceRequired: 'GL, payroll, cash records, adjustment support, working capital and asset schedules.', decisionAffected: 'Price ceiling and financing case.', evidenceIds: refs },
      { rank: 3, area: 'Control and seller commitment', whyItMatters: 'The buyer needs a credible consent and handover path.', evidenceRequired: 'Ownership documents, approvals and an executable seller transition proposal.', decisionAffected: 'Exclusivity and LOI readiness.', evidenceIds: refs },
    ],
    actionMap: {
      investigate: [{ item: 'Request one coordinated evidence package', rationale: 'Test customer retention, owner replacement and adjusted earnings together, since each affects the others.', evidenceIds: refs }],
      price: [{ item: 'Establish standalone value before discussing buyer savings', rationale: 'The buyer’s existing dispatch and finance capabilities create buyer-owned synergy. The seller’s ask needs a supported standalone earnings case.', evidenceIds: refs }],
      protect: [{ item: 'Make transition support specific and measurable', rationale: 'If the seller remains and can influence results, contingent consideration may support alignment. Define responsibilities and accounting treatment; an earnout does not cure an unworkable operating model.', evidenceIds: refs }],
    },
    walkAwayConditions: [{ item: 'Stop if the modeled downside cannot be survived', rationale: 'Apply simultaneous revenue and margin stress with required capital and financing costs. No survivability conclusion is currently established.', evidenceIds: refs }, { item: 'Stop if there is no credible path to control or the ask exceeds the private ceiling', rationale: 'Scarcity must be evidenced to justify further investigation of a control exception. A ceiling remains binding even for an attractive asset.', evidenceIds: refs }],
    uncertaintySurface: [{ unknown: 'Transferable earnings, financing terms and required capital', decisionConsequence: 'No supportable valuation or affordability conclusion can be issued.', evidenceRequired: 'Reconciled records, accepted adjustments, replacement costs and financing scenarios.', evidenceIds: refs }, { unknown: 'Current competitive facts and market dynamics', decisionConsequence: 'The illustrative competitive interpretation cannot substitute for research into a real target.', evidenceRequired: 'A real public identity and cited company, competitor and industry sources.', evidenceIds: refs }],
    rankedSellerQuestions: [
      { rank: 1, question: 'What decisions would still reach you if you stopped answering calls tomorrow?', reason: 'Identifies operating dependencies behind the claimed independence.', decisionAffected: 'Transition staffing and cost.', evidenceIds: refs },
      { rank: 2, question: 'What has the largest customer actually agreed to about renewal and a change of ownership?', reason: 'Separates a durable contract from an owner-held relationship.', decisionAffected: 'Retention assumptions and downside.', evidenceIds: refs },
      { rank: 3, question: 'Which of the $120K adjustments would disappear after closing, and who performs the owner’s work?', reason: 'Tests the quality of the earnings the buyer is being asked to purchase.', decisionAffected: 'Normalization and price discipline.', evidenceIds: refs },
      { rank: 4, question: 'Whose consent is needed to sell, and have they agreed to the proposed structure?', reason: 'Tests the founder’s ability to deliver the transaction.', decisionAffected: 'Whether the process can credibly advance.', evidenceIds: refs },
    ],
    nextDecision: { commitment: 'Authorize a focused initial diligence review after receiving the priority evidence package.', evidenceGate: 'A credible customer/owner transition path, ownership and consent records, and enough financial records to start reconstructing earnings.', stopCondition: 'Unresolved control without a credible exception, economics above the buyer’s ceiling, or a non-survivable modeled downside.' },
    limitations: ['Illustrative sample written for a fictional case. It is not a live research or production-model run.', 'All numbers, companies and competitor names are demonstration inputs. No financial records, contracts, ownership documents or public sources were verified.', 'No valuation, financing approval, calculated return or LOI recommendation is supplied.'],
  },
};
