import fs from 'node:fs';
import { models, modelBody, modelSources } from './model-content.mjs';
import { handbooks, handbookBody } from './handbook-content.mjs';
const dir='site-foundation/launch';fs.mkdirSync(dir,{recursive:true});
const read=n=>JSON.parse(fs.readFileSync(`${dir}/${n}`,'utf8'));
const write=(n,v)=>fs.writeFileSync(`${dir}/${n}`,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
const S='https://www.mikeye.com', M='https://mcp.mikeye.com', date='2026-09-08';
const manifest=JSON.parse(fs.readFileSync('site-foundation/content-manifest.json'));
const prior=read('global-code-before.json').result.find(x=>x.location==='head').content;
const before=JSON.parse(prior.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1]);
const oldPerson=before['@graph'].find(x=>x['@type']==='Person');
const topics=manifest.topics.map(t=>({'@type':'DefinedTerm','@id':`${S}/m-and-a#${t.slug}`,name:t.name,description:t.summary,termCode:t.slug,inDefinedTermSet:{'@id':`${S}/m-and-a#ontology`}}));
const person={'@type':'Person','@id':`${S}/#person`,name:'Mike Ye',givenName:'Mike',familyName:'Ye',alternateName:['Michael Ye'],url:`${S}/about`,image:oldPerson.image,jobTitle:'M&A and Corporate Development Executive',description:'Mike Ye brings 25 years of experience across acquisitions, divestitures, corporate development, strategic finance, and portfolio exits in media, healthcare, retail, and technology.',sameAs:oldPerson.sameAs,alumniOf:oldPerson.alumniOf,knowsLanguage:['en','zh'],knowsAbout:topics.map(t=>({'@id':t['@id'],name:t.name})),subjectOf:[{'@id':`${S}/about#webpage`},{'@id':`${S}/about/record#webpage`}]};
const website={'@type':'WebSite','@id':`${S}/#website`,url:S+'/',name:'Mike Ye — Practical M&A Library',description:'Practical M&A judgment, valuation models, due diligence and integration handbooks, transaction lessons, and corporate development frameworks by Mike Ye.',inLanguage:'en-US',publisher:{'@id':person['@id']},about:topics.map(t=>({'@id':t['@id']})),hasPart:['/m-and-a','/tools-and-models','/intelligence','/glossary','/podcast','/about','/exit'].map(p=>({'@id':S+p+'#webpage'}))};
const graph=nodes=>({'@context':'https://schema.org','@graph':nodes});
const json=v=>JSON.stringify(v).replaceAll('<','\\u003c');
const tag=v=>`<script type="application/ld+json">${json(v)}</script>`;
const crumb=(items)=>({'@type':'BreadcrumbList','@id':items.at(-1)[1]+'#breadcrumbs',itemListElement:items.map(([name,item],i)=>({'@type':'ListItem',position:i+1,name,item}))});
const page=(url,name,description,type='CollectionPage')=>({'@type':type,'@id':url+'#webpage',url,name,description,inLanguage:'en-US',isPartOf:{'@id':S+'/#website'},publisher:{'@id':S+'/#person'}});
const stripSchema=s=>s.replace(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi,'').replace(/<meta\b[^>]*name=["']robots["'][^>]*>/gi,'');
const globalCode=stripSchema(prior).replace(/<!-- MikeYe \| Ella[\s\S]*?-->/g,'').replace('<!-- /MikeYe Ella context -->','').trim();
write('global-head.html',globalCode+'\n'+tag(graph([person,website]))+`\n<link rel="alternate" type="application/ld+json" href="${M}/ontology.json" title="Mike Ye M&A ontology">\n<link rel="alternate" type="application/json" href="${M}/datasets/ma-library.json" title="M&A resource inventory">\n<link rel="alternate" type="text/plain" href="${M}/llms.txt" title="Mike Ye machine-readable guide">\n`);
write('global-footer.html','');
const resources=manifest.resources.map(r=>{const n={...r};if(n.proposedPath){n.url=S+n.proposedPath;n.status='published';n.publicationDate=date;n.contentReviewedAt=date;n.cmsStatus='ready-for-publication';n.version=n.format==='Handbook'?'1.0':n.version;}return n;});
const getResource=r=>{
 const isNew=!!r.proposedPath;const url=r.url;const schema={'@type':isNew?['CreativeWork','LearningResource']:'CreativeWork','@id':url+'#resource',url,name:r.name,description:r.summary,author:{'@id':person['@id']},publisher:{'@id':person['@id']},inLanguage:'en-US',about:{'@id':`${S}/m-and-a#${r.topic}`},isPartOf:{'@id':`${S}/m-and-a#library`},isAccessibleForFree:true};
 if(isNew){schema.learningResourceType=r.format==='Model'?'Valuation model and Excel workbook':'Practical handbook and Excel working pack';schema.teaches=r.decision;schema.datePublished=date;schema.dateModified=date;schema.version=r.version;schema.mainEntityOfPage={'@id':url+'#webpage'};}
 if(r.download){schema.encoding={'@type':'MediaObject','@id':url+'#workbook',name:r.download.filename,contentUrl:r.download.url,encodingFormat:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',contentSize:r.download.bytes+' bytes'};}
 return schema;
};
const schemas=resources.map(getResource);
const itemlist=(id,rs)=>({'@type':'ItemList','@id':id,numberOfItems:rs.length,itemListElement:rs.map((r,i)=>({'@type':'ListItem',position:i+1,item:{'@id':r.url+'#resource',url:r.url,name:r.name}}))});
const library=page(S+'/m-and-a','M&A Library | Mike Ye','Practical M&A resources across valuation, due diligence, integration, deal strategy, and corporate development.');library.mainEntity={'@id':S+'/m-and-a#library'};library.about=topics.map(t=>({'@id':t['@id']}));
const libGraph=graph([library,{'@type':'Collection','@id':S+'/m-and-a#library',name:'Mike Ye Practical M&A Library',url:S+'/m-and-a',hasPart:schemas.map(r=>({'@id':r['@id']})),creator:{'@id':person['@id']}},{'@type':'DefinedTermSet','@id':S+'/m-and-a#ontology',name:'Mike Ye M&A deal lifecycle',description:'The subject structure used to organize the practical M&A library.',hasDefinedTerm:topics},itemlist(S+'/m-and-a#resources',resources),crumb([['Home',S+'/'],['M&A Library',S+'/m-and-a']]),...schemas]);
const toolsResources=resources.filter(r=>r.download||r.id==='exit-valuation');const tp=page(S+'/tools-and-models','M&A Valuation Models & Practical Tools | Mike Ye','Five downloadable company valuation models, an Exit Desk valuation calculator, and practical diligence and integration working packs.');tp.mainEntity={'@id':S+'/tools-and-models#tools'};
const toolsGraph=graph([tp,itemlist(S+'/tools-and-models#tools',toolsResources),crumb([['Home',S+'/'],['Tools & Models',S+'/tools-and-models']]),...schemas.filter(s=>toolsResources.some(r=>r.url===s.url))]);
const hp=page(S+'/','The Deal Is Only the Beginning. | Mike Ye','M&A frameworks, valuation models, and practical tools built from 25 years of acquiring businesses, integrating operations, and creating value.','WebPage');hp.about={'@id':person['@id']};hp.hasPart=[{'@id':S+'/m-and-a#library'},{'@id':S+'/tools-and-models#tools'}];
write('home-head.html',`<link rel="canonical" href="${S}/">\n`+tag(graph([hp]))+'\n');
write('library-head.html',`<link rel="canonical" href="${S}/m-and-a">\n`+tag(libGraph)+'\n');
write('tools-head.html',`<link rel="canonical" href="${S}/tools-and-models">\n`+tag(toolsGraph)+'\n');
write('ontology.json',graph([person,website,{'@type':'DefinedTermSet','@id':S+'/m-and-a#ontology',name:'Mike Ye M&A deal lifecycle',hasDefinedTerm:topics},...schemas]));
write('ma-library.json',{version:'1.0',updated:date,entity:{id:person['@id'],name:'Mike Ye',website:S+'/'},scope:'Published M&A learning resources and working tools',topics,resources:resources.map(r=>({id:r.id,name:r.name,type:r.format,topic:r.topic,url:r.url,summary:r.summary,decision:r.decision||null,version:r.version||null,publicationDate:r.publicationDate||null,valuationDate:r.valuationDate||null,download:r.download||null})),products:[{name:'Exit Desk',url:S+'/exit',status:'available'},{name:'Acquisition Lens',status:'in development; not accepting purchases'}]});
const cms=read('cms-before.json').resources;
// Native schema fields render CMS bindings server-side. The page freeform-code
// API rejects nonempty HTML on this site, so no custom-head binding is emitted.
write('resource-native-schema.json',JSON.parse(fs.readFileSync('site-foundation/resource-template.schema.json','utf8')));
write('home-native.html','<div class="my1-root"><a class="my1-skip" href="#main-content">Skip to content</a>'+['header.html','main.html','footer.html'].map(n=>fs.readFileSync('site-foundation/'+n,'utf8')).join('\n')+'</div>');
const itemUpdates=resources.map(r=>{const old=cms.find(i=>i.id===r.webflowItemId||i.fieldData['canonical-url']===r.url);if(!old)throw Error('Missing CMS '+r.id);const isNew=!!r.proposedPath;const pg=page(r.url,r.name,r.summary,'WebPage');pg.mainEntity={'@id':r.url+'#resource'};const schema=graph([pg,getResource(r),crumb([['Home',S+'/'],['M&A Library',S+'/m-and-a'],[r.name,r.url]])]);const fields={'canonical-url':r.url,'structured-data-json':json(schema),'editorial-state':isNew?'c79727d3406a8cb682d2113ea8cf9ea0':'4fa171d81283cc868bd25a437fdffe49'};if(isNew){fields.author='Mike Ye';fields['reviewed-date']=date+'T00:00:00Z';fields.version=r.version;const model=models.find(m=>m.id===r.id);const book=handbooks.find(b=>b.id===r.id);if(model){fields.methodology=modelBody(model);fields['source-notes']=modelSources(model);}else{fields.methodology=handbookBody(book).replace('<p><strong>Editorial draft · Prepared for Mike’s review</strong></p>','');fields['source-notes']=book.sourceNotes.replace(/Draft 0.2 · Prepared for Mike Ye’s editorial review\./,'Version 1.0 · Published September 8, 2026.');}}return {id:old.id,isDraft:false,fieldData:fields};});
write('resource-updates.json',itemUpdates);
write('publication-resources.json',resources);
const hubs=read('hub-code-before.json');const updates=[];
for(const x of hubs){const id=x.label.split(' ')[0],p=x.label.split(' ')[1];let head=x.result.find(b=>b.location==='head').content;
 if(p==='/intelligence'){
  const frames=manifest.existingPages?.filter?.(p=>p.publishedPath?.startsWith('/intelligence/'))||[];
  const links=[['Judgment as a Service','judgment-as-a-service'],['Dependency vs Leverage','dependency-vs-leverage'],['Timing Asymmetry','timing-asymmetry'],['Signal vs Narrative','signal-vs-narrative'],['Scarcity vs Growth','scarcity-vs-growth']];
  const pg=page(S+p,'Decision Frameworks | Mike Ye','Five decision frameworks for evaluating evidence, timing, leverage, scarcity, and the transfer of judgment.');pg.about={'@id':S+'/m-and-a#corporate-development'};pg.mainEntity={'@id':S+p+'#frames'};
  head=stripSchema(head)+tag(graph([pg,{'@type':'ItemList','@id':S+p+'#frames',numberOfItems:5,itemListElement:links.map(([name,slug],i)=>({'@type':'ListItem',position:i+1,item:{'@type':'CreativeWork',name,url:S+p+'/'+slug,'@id':S+p+'/'+slug+'#frame',author:{'@id':person['@id']}}}))},crumb([['Home',S+'/'],['Decision Frameworks',S+p]])]));
 }else if(p==='/glossary'){
  // Preserve existing term definitions and styling; relocate the glossary under the parent M&A library.
  head=head.replace(/\{\s*"@type":\s*"ListItem",\s*"position":\s*2,\s*"name":\s*"Exit Desk",\s*"item":\s*"https:\/\/www\.mikeye\.com\/exit"\s*\}/g,'{"@type":"ListItem","position":2,"name":"M&A Library","item":"https://www.mikeye.com/m-and-a"}');
  head=head.replace(/"name":\s*"Exit Desk Glossary/g,'"name": "M&A Glossary');
 }
 if(head!==x.result.find(b=>b.location==='head').content)updates.push({id,head});
}
write('existing-hub-updates.json',updates);
write('llms.txt',`# Mike Ye — Practical M&A Library\n\n> M&A judgment made practical through valuation models, diligence and integration handbooks, transaction lessons, and decision frameworks.\n\nUpdated: ${date}\nCanonical identity: ${S}/#person\n\n## Authority and scope\n\nMike Ye is an M&A and corporate development executive with 25 years of experience across media, healthcare, retail, and technology. MikeYe.com is his public M&A knowledge and tool library. Exit Desk is its seller-facing application. Acquisition Lens is in development and is not accepting purchases.\n\n## Start here\n\n- [M&A Library](${S}/m-and-a): Deal lifecycle topics and practical resources.\n- [Tools & Models](${S}/tools-and-models): Five Excel valuation models, two working packs, and the existing valuation calculator.\n- [About Mike](${S}/about): Experience and selected transactions.\n- [PMC masthead records](${S}/about/record): Evidence of title and tenure at Penske Media; these records are not a list of Mike's deals.\n- [Decision Frameworks](${S}/intelligence): Mike's judgment frameworks.\n- [M&A Glossary](${S}/glossary): Practical definitions and buyer/seller implications.\n- [The Mike Ye Briefing](${S}/podcast): Podcast episodes.\n\n## Resources\n\n${resources.map(r=>`- [${r.name}](${r.url}): ${r.summary}${r.download?' Includes an Excel download.':''}`).join('\n')}\n\n## How to use the materials\n\nCite the relevant HTML guide for methodology and the versioned workbook for calculations. Company models use a September 4, 2026 valuation date; forecasts and scenario inputs are assumptions, not later reported results. Company examples do not imply Mike participated in their transactions. Hypothetical examples are labeled in the handbooks.\n\n## Machine access\n\n- [Resource inventory](${M}/datasets/ma-library.json)\n- [M&A ontology](${M}/ontology.json)\n- [MCP tool registry](${M}/.well-known/tool-registry.json)\n\n## Applied products\n\n- [Exit Desk](${S}/exit): Seller exit readiness.\n- [Free readiness diagnostic](${S}/exit/score)\n\n## Related entities\n\nMike also founded exmxc.ai and TrailGenic. Ella's canonical identity is at https://ellaentity.ai/ella; her flagship subject is longevity and human adaptation. Those are related entities, not substitutes for Mike's M&A authority.\n`);
console.log('Built global, hub and per-resource schema, ontology, resource inventory and machine guide.');
