import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..", "site-foundation");
export const escapeHTML = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll('"', "&quot;");
export const handbooks = ["deal-workflow", "workflow-diligence", "integration-continuity"].map((id) => JSON.parse(readFileSync(resolve(root, "editorial", id + ".json"), "utf8")));
export const workbookLink = (book) => book.download?.downloadVerified ? `<p class="my1-small"><a class="my1-text-link" href="${escapeHTML(book.download.url)}">Download Excel working pack →</a></p>` : "";
export const handbookBody = (book) => '<p><strong>Editorial draft · Prepared for Mike’s review</strong></p>' + book.sections.map((section) => `<h2>${escapeHTML(section.heading)}</h2>${section.html}`).join("");
export const draftCatalogue = (local = false) => `<section class="my1-section" id="draft-guides"><p class="my1-eyebrow">New guides · Editorial drafts</p><h2 class="my1-section-title">Pick a task. Start there.</h2><p class="my1-copy">Two practical guides built from Mike’s acquisition principles. Prepared for his editorial review; not yet published.</p><div class="my2-list">${handbooks.map((book) => `<article class="my3-draft-card"><p class="my1-eyebrow">${book.topic === "due-diligence" ? "Due diligence" : "Integration"}</p><h3 class="my1-card-title">${escapeHTML(book.name)}</h3><p class="my1-copy">${escapeHTML(book.summary)}</p><a class="my1-text-link" href="${local ? "#" + book.id : "/ma-resources/" + book.slug}">Read the draft guide →</a>${workbookLink(book)}</article>`).join("")}</div></section>`;
export const fullDraftGuides = () => `<section class="my3-handbooks" aria-label="Draft handbooks">${handbooks.map((book) => `<article class="my2-reading" id="${book.id}"><a class="my1-text-link" href="#draft-guides">Back to the two guides</a><p class="my1-eyebrow">Handbook · Editorial draft ${escapeHTML(book.version.replace("-draft", ""))}</p><h2 class="my2-title">${escapeHTML(book.name)}</h2><p class="my1-lead">${escapeHTML(book.summary)}</p><div class="my2-decision"><h3 class="my1-topic-title">What this helps you decide</h3><p class="my1-copy">${escapeHTML(book.decision)}</p></div><div class="my3-guide-body">${book.sections.map((section) => `<section class="my3-guide-section"><h3 class="my1-card-title">${escapeHTML(section.heading)}</h3>${section.html}</section>`).join("")}</div><footer class="my2-provenance">${book.sourceNotes}<p>Prepared from Mike Ye’s documented principles with Ella. Educational guidance; adapt the work and involve the appropriate professionals for the transaction.</p></footer></article>`).join("")}</section>`;
