import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { escapeHTML as esc, handbooks } from "./handbook-content.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..", "site-foundation");
export const models = JSON.parse(readFileSync(resolve(root, "editorial/company-models.json"), "utf8"));
export const methods = [
  ["Trading comparables", "What do similar listed businesses trade for?", "Choose peers for how they earn money and their growth, margins, and risk. A familiar name is not enough."],
  ["Discounted cash flow (DCF)", "What is the future cash generation worth today?", "Make the growth, margin, investment, and risk assumptions explicit. A precise output can still rest on uncertain inputs."],
  ["Precedent transactions", "What have buyers paid for comparable businesses?", "Check the date, stake, business mix, and financial measure. A control deal may include benefits a new buyer cannot reproduce."],
  ["Sum-of-the-parts", "What are distinct businesses worth separately?", "Use only where segment economics support the work. Deduct central costs and obligations once; do not invent missing segment profit."],
  ["Acquisition returns", "What could this buyer afford to pay?", "State the financing and return hurdle. This is a buyer-specific price ceiling, not an independent measure of standalone value."]
];
const href = (model, local) => local ? "#" + model.id : "/ma-resources/" + model.slug;
export const modelStatus = model => model.download?.downloadVerified ? `<p class="my5-status"><strong>Excel model available.</strong> Version ${esc(model.download.version)} · Valuation date: ${esc(model.valuationDate)}.</p><p><a class="my1-text-link" href="${esc(model.download.url)}">Download Excel model</a> · ${Math.round(model.download.bytes / 1024)} KB</p>` : '<p class="my5-status"><strong>Workbook coming soon.</strong> This guide is a starting point. The financial model, valuation ranges, and download are not yet available.</p>';
export const modelSources = model => `<p>Mike Ye · Workbook version ${esc(model.download.version)} · Valuation date: ${esc(model.valuationDate)}. Sources, adjustments, and assumptions are documented in the workbook. These are dated company examples; refresh the inputs before using a new valuation date.</p><p>Company reference material: ${model.sources.map(s => `<a href="${esc(s.url)}">${esc(s.title)}</a>`).join("; ")}.</p><p>Company examples support learning about valuation. No participation by Mike in a transaction involving these companies is implied. <a href="https://www.mikeye.com/about">About Mike</a> contains his selected deals.</p>`;
export const methodGuide = () => `<section class="my1-section" id="valuation-methods"><p class="my1-eyebrow">Choose the question before the method</p><h2 class="my1-section-title">Five ways to look at value.</h2><p class="my1-copy">The company models offer these five perspectives on value. Each answers a different question; compare the evidence before choosing a range.</p><div class="my2-list">${methods.map(([name, question, limit]) => `<article class="my5-method"><h3 class="my1-card-title">${esc(name)}</h3><p class="my1-copy">${esc(question)}</p><p class="my1-small">${esc(limit)}</p></article>`).join("")}</div><p class="my1-copy">A low DCF and a high peer multiple are a reason to investigate the assumptions. Averaging the two does not resolve the disagreement.</p></section>`;
export const modelBody = (model, local = false) => `${modelStatus(model)}<h2>Start with one piece of the business</h2><p>${esc(model.firstTask)}</p><h2>Three things to work through</h2>${model.drivers.map(d=>`<h3>${esc(d.name)}</h3><p><strong>Ask:</strong> ${esc(d.question)}</p><p><strong>Find:</strong> ${esc(d.evidence)}</p><p><strong>Then decide:</strong> ${esc(d.consequence)}</p>`).join("")}<h2>Where the valuation can go wrong</h2><p>${esc(model.watchout)}</p><h2>Apply Mike’s judgment</h2><p>${esc(model.judgment)}</p><p>Write down what must be true for the price to make sense. Test lower revenue and lower margins together, including financing and required investment. Keep buyer-created synergies separate from the business’s standalone value.</p><h2>Open the workbook and try one change</h2><ol><li>Read <strong>Start Here</strong>, then open <strong>Valuation Summary</strong> to see the range of methods.</li><li>Review <strong>Assumptions</strong> and <strong>Sources &amp; Adjustments</strong>. Separate reported figures from assumptions before changing the case.</li><li>Change one operating assumption, then test lower revenue and lower margins together. Follow the effect through <strong>Operating Forecast</strong>, <strong>DCF</strong>, and <strong>Sensitivities</strong>.</li><li>Read <strong>Checks</strong> after each change. Resolve a failed check or funding shortfall before relying on the result.</li></ol><p>${esc(model.workbookFocus)}</p><h2>Compare the answers</h2><p>Use Trading Comps and DCF to compare market pricing with the cash the business can generate. The Transactions and Sum-of-the-Parts sheets add perspectives where the inputs support them; read their assumptions before treating the outputs as evidence. Acquisition Returns is a buyer-affordability exercise, with its own financing and return assumptions.</p><p>Check enterprise value (the operating business) separately from equity value (what remains for shareholders after the relevant cash, debt, and other adjustments). If methods disagree, identify the assumption causing the gap before choosing a range.</p><p><a href="${local ? "#valuation-methods" : "/tools-and-models#valuation-methods"}">Choose a valuation method</a></p><h2>Copy this assumption note</h2><ul><li>Assumption that matters: ___</li><li>Evidence supporting it: ___</li><li>What is still unknown: ___</li><li>What changes in the downside: ___</li><li>Effect on cash, price, or the handover: ___</li><li>Next evidence to obtain and owner: ___</li></ul><h2>Carry the finding into the deal</h2><p><a href="${local ? "#workflow-diligence" : "/ma-resources/before-you-buy-follow-the-work"}">Before You Buy: Follow the Work</a> helps test the operating assumptions. <a href="${local ? "#integration-continuity" : "/ma-resources/after-the-deal-keep-the-business-working"}">After the Deal: Keep the Business Working</a> helps assign the changes and protect continuity.</p>`;
export const modelCatalogue = (local = false) => `<section class="my1-section" id="company-models"><p class="my1-eyebrow">Company valuation models · Excel downloads</p><h2 class="my1-section-title">Learn through a real business.</h2><p class="my1-copy">Five downloadable company models, each with a practical guide. Start with the business, change an assumption, and follow what happens to value.</p><div class="my2-list">${models.map(m=>`<article class="my5-model-card"><p class="my1-eyebrow">${esc(m.industry)} · ${esc(m.ticker)}</p><h3 class="my1-card-title">${esc(m.name)}</h3><p class="my1-copy">${esc(m.summary)}</p><p class="my5-status">Excel model · Version ${esc(m.download.version)}</p><p><a class="my1-text-link" href="${esc(m.download.url)}">Download Excel model</a></p><a class="my1-text-link" href="${href(m, local)}">Read the model guide</a></article>`).join("")}</div></section>`;
export const toolsHub = (local = false) => `<section class="my2-intro" id="tools-and-models"><p class="my1-eyebrow">Tools &amp; Models</p><h2 class="my2-title">Put the analysis to work.</h2><p class="my1-copy">Choose the work in front of you: run the deal, test a business, plan the handover, or explore value.</p><div class="my2-topic-links"><a class="my1-text-link" href="#working-tools">Use a working tool</a><a class="my1-text-link" href="#company-models">Explore company models</a><a class="my1-text-link" href="#valuation-methods">Choose a valuation method</a></div></section><section class="my1-section" id="working-tools"><h2 class="my1-section-title">Start with a tool you can use.</h2><div class="my2-list"><article class="my5-tool-card"><p class="my1-eyebrow">Published calculator</p><h3 class="my1-card-title">Business valuation scenarios</h3><p class="my1-copy">Explore indicative seller valuation scenarios in Exit Desk. The calculator serves a different purpose from the public-company models below.</p><a class="my1-text-link" href="https://www.mikeye.com/exit/valuation">Open the valuation calculator</a></article>${handbooks.map(b=>`<article class="my5-tool-card"><p class="my1-eyebrow">Excel checklist · Version ${esc(b.download.version)}</p><h3 class="my1-card-title">${b.id === "deal-workflow" ? "End-to-end M&A deal workflow" : b.id === "workflow-diligence" ? "M&A due diligence checklist" : "Post-deal integration checklist"}</h3><p class="my1-copy">${esc(b.summary)}</p><p><a class="my1-text-link" href="${esc(b.download.url)}">Download Excel checklist</a></p><a class="my1-text-link" href="${local ? "#" + b.id : "/ma-resources/" + b.slug}">Read the companion guide</a></article>`).join("")}</div></section>${modelCatalogue(local)}${methodGuide()}`;
export const fullModelGuides = () => `<section aria-label="Company valuation model guides">${models.map(m=>`<article class="my2-reading" id="${m.id}"><a class="my1-text-link" href="#company-models">Back to company models</a><p class="my1-eyebrow">${esc(m.industry)} · ${esc(m.ticker)} · Model guide</p><h2 class="my2-title">${esc(m.name)}</h2><p class="my1-lead">${esc(m.summary)}</p><div class="my2-decision"><h3 class="my1-topic-title">What this helps you decide</h3><p class="my1-copy">${esc(m.decision)}</p></div><div class="my3-guide-body">${modelBody(m, true)}</div><footer class="my2-provenance">${modelSources(m)}</footer></article>`).join("")}</section>`;
