import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { escapeHTML as esc, handbooks } from "./handbook-content.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..", "site-foundation");
export const models = JSON.parse(readFileSync(resolve(root, "editorial/company-models.json"), "utf8"));
export const methods = [
  ["Trading comparables", "What do similar listed businesses trade for?", "Choose peers for how they earn money and their growth, margins, and risk. A familiar name is not enough."],
  ["Discounted cash flow (DCF)", "What is the future cash generation worth today?", "Make the growth, margin, investment, and risk assumptions explicit. A precise output can still rest on uncertain inputs."],
  ["Precedent transactions", "What have buyers paid for comparable businesses?", "Check the date, stake, business mix, and financial measure. A control deal may include benefits a new buyer cannot reproduce."],
  ["Sum-of-the-parts", "What are distinct businesses worth separately?", "Use only where segment economics support the work. Deduct central costs and obligations once; do not invent missing segment profit."],
  ["Acquisition returns", "What could this buyer afford to pay?", "State the financing and return hurdle. This is a buyer-specific price ceiling, not an independent measure of standalone value."]
];
const href = (model, local) => local ? "#" + model.id : "/ma-resources/" + model.slug;
export const modelStatus = () => '<p class="my5-status"><strong>Workbook coming soon.</strong> This guide is a starting point. The financial model, valuation ranges, and download are not yet available.</p>';
export const modelSources = model => `<p>Editorial draft 0.1 · Prepared for Mike Ye’s review. These are practical applications of Mike’s saved acquisition principles, not quotations or a completed company valuation.</p><p>Company reference material: ${model.sources.map(s => `<a href="${esc(s.url)}">${esc(s.title)}</a>`).join("; ")}.</p><p>Company examples support learning about valuation. No participation by Mike in a transaction involving these companies is implied. <a href="https://www.mikeye.com/about">About Mike</a> contains his selected deals.</p>`;
export const methodGuide = () => `<section class="my1-section" id="valuation-methods"><p class="my1-eyebrow">Choose the question before the method</p><h2 class="my1-section-title">Five ways to look at value.</h2><p class="my1-copy">These are the planned approaches for the company models. Each answers a different question; compare the evidence before choosing a range.</p><div class="my2-list">${methods.map(([name, question, limit]) => `<article class="my5-method"><h3 class="my1-card-title">${esc(name)}</h3><p class="my1-copy">${esc(question)}</p><p class="my1-small">${esc(limit)}</p></article>`).join("")}</div><p class="my1-copy">A low DCF and a high peer multiple are a reason to investigate the assumptions. Averaging the two does not resolve the disagreement.</p></section>`;
export const modelBody = (model, local = false) => `${modelStatus()}<h2>Start with one piece of the business</h2><p>${esc(model.firstTask)}</p><h2>Three things to work through</h2>${model.drivers.map(d=>`<h3>${esc(d.name)}</h3><p><strong>Ask:</strong> ${esc(d.question)}</p><p><strong>Find:</strong> ${esc(d.evidence)}</p><p><strong>Then decide:</strong> ${esc(d.consequence)}</p>`).join("")}<h2>Where the valuation can go wrong</h2><p>${esc(model.watchout)}</p><h2>Apply Mike’s judgment</h2><p>${esc(model.judgment)}</p><p>Write down what must be true for the price to make sense. Test lower revenue and lower margins together, including financing and required investment. Keep buyer-created synergies separate from the business’s standalone value.</p><h2>What the workbook is being built to do</h2><p>The planned workbook will connect historical results to an operating forecast, trading comparables, and discounted cash flow. Transaction comparisons and a sum-of-the-parts view will be included only where the evidence supports them. A separate acquisition-return case will show buyer affordability.</p><p>Once it is available, start with the base case, change one assumption, then test a combined downside. Check enterprise value (the operating business) separately from equity value (what remains for shareholders after the relevant cash, debt, and other adjustments).</p><p><a href="${local ? "#valuation-methods" : "/tools-and-models#valuation-methods"}">Choose a valuation method</a></p><h2>Copy this assumption note</h2><ul><li>Assumption that matters: ___</li><li>Evidence supporting it: ___</li><li>What is still unknown: ___</li><li>What changes in the downside: ___</li><li>Effect on cash, price, or the handover: ___</li><li>Next evidence to obtain and owner: ___</li></ul><h2>Carry the finding into the deal</h2><p><a href="${local ? "#workflow-diligence" : "/ma-resources/before-you-buy-follow-the-work"}">Before You Buy: Follow the Work</a> helps test the operating assumptions. <a href="${local ? "#integration-continuity" : "/ma-resources/after-the-deal-keep-the-business-working"}">After the Deal: Keep the Business Working</a> helps assign the changes and protect continuity.</p>`;
export const modelCatalogue = (local = false) => `<section class="my1-section" id="company-models"><p class="my1-eyebrow">Company valuation models · Coming soon</p><h2 class="my1-section-title">Learn through a real business.</h2><p class="my1-copy">Five company examples, with a practical starting guide for each. Excel downloads and valuation results will follow when the models are complete and checked.</p><div class="my2-list">${models.map(m=>`<article class="my5-model-card"><p class="my1-eyebrow">${esc(m.industry)} · ${esc(m.ticker)}</p><h3 class="my1-card-title">${esc(m.name)}</h3><p class="my1-copy">${esc(m.summary)}</p><p class="my5-status">Workbook coming soon</p><a class="my1-text-link" href="${href(m, local)}">Read the starting guide</a></article>`).join("")}</div></section>`;
export const toolsHub = (local = false) => `<section class="my2-intro" id="tools-and-models"><p class="my1-eyebrow">Tools &amp; Models</p><h2 class="my2-title">Put the analysis to work.</h2><p class="my1-copy">Choose the work in front of you: explore value, test a business, or plan the handover.</p><div class="my2-topic-links"><a class="my1-text-link" href="#working-tools">Use a working tool</a><a class="my1-text-link" href="#company-models">Explore company models</a><a class="my1-text-link" href="#valuation-methods">Choose a valuation method</a></div></section><section class="my1-section" id="working-tools"><h2 class="my1-section-title">Start with a tool you can use.</h2><div class="my2-list"><article class="my5-tool-card"><p class="my1-eyebrow">Published calculator</p><h3 class="my1-card-title">Business valuation scenarios</h3><p class="my1-copy">Explore indicative seller valuation scenarios in Exit Desk. The calculator serves a different purpose from the public-company models below.</p><a class="my1-text-link" href="https://www.mikeye.com/exit/valuation">Open the valuation calculator</a></article>${handbooks.map(b=>`<article class="my5-tool-card"><p class="my1-eyebrow">Excel working pack · Draft 0.1</p><h3 class="my1-card-title">${b.id === "workflow-diligence" ? "Diligence working pack" : "Integration working pack"}</h3><p class="my1-copy">${esc(b.summary)}</p><p><a class="my1-text-link" href="${esc(b.download.url)}">Download Excel working pack</a></p><a class="my1-text-link" href="${local ? "#" + b.id : "/ma-resources/" + b.slug}">Read the companion guide</a></article>`).join("")}</div></section>${modelCatalogue(local)}${methodGuide()}`;
export const fullModelGuides = () => `<section aria-label="Company model starting guides">${models.map(m=>`<article class="my2-reading" id="${m.id}"><a class="my1-text-link" href="#company-models">Back to company models</a><p class="my1-eyebrow">${esc(m.industry)} · ${esc(m.ticker)} · Draft guide</p><h2 class="my2-title">${esc(m.name)}</h2><p class="my1-lead">${esc(m.summary)}</p><div class="my2-decision"><h3 class="my1-topic-title">What this helps you decide</h3><p class="my1-copy">${esc(m.decision)}</p></div><div class="my3-guide-body">${modelBody(m, true)}</div><footer class="my2-provenance">${modelSources(m)}</footer></article>`).join("")}</section>`;
